language: ruby
cache: bundler
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: gh-pages
  email: angelo_22@outlook.com
  name: Angelo Banse
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
